const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const BUILD_DIR = path.resolve(__dirname, '../../build');
const SW_FILE = path.resolve(BUILD_DIR, 'service-worker.js');

// ===== 1. Собираем все файлы из /build =====
function getAllFiles(dir, prefix = '/') {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getAllFiles(filePath, path.join(prefix, file)));
    } else if (!filePath.endsWith('service-worker.js')) {
      results.push(path.join(prefix, file));
    }
  });
  return results;
}

const files = getAllFiles(BUILD_DIR);

// ===== 2. Создаём хэш версии на основе содержимого файлов =====
const hash = crypto
  .createHash('sha256')
  .update(files.map(f => fs.readFileSync(path.join(BUILD_DIR, f))).join(''))
  .digest('hex')
  .substring(0, 12);

const CACHE_NAME = `rise-cache-${hash}`;

console.log(`🧩 Создание service worker (version: ${CACHE_NAME})`);
console.log(`📦 Файлов добавлено в кеш: ${files.length}`);

// ===== 3. Генерируем содержимое SW =====
const swContent = `
// ===== Auto-generated by generate-sw.js =====
const CACHE_NAME = '${CACHE_NAME}';
const STATIC_ASSETS = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[ServiceWorker] Caching', STATIC_ASSETS.length, 'files');
      return cache.addAll(STATIC_ASSETS);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => 
      Promise.all(
        keys
          .filter((key) => key.startsWith('rise-cache-') && key !== CACHE_NAME)
          .map((key) => {
            console.log('[ServiceWorker] Removing old cache', key);
            return caches.delete(key);
          })
      )
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const requestUrl = new URL(event.request.url);

  // Не кэшируем запросы к API или Barba transitions
  if (requestUrl.pathname.startsWith('/api/') || requestUrl.searchParams.has('barba')) {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      const fetchPromise = fetch(event.request)
        .then((networkResponse) => {
          // Обновляем кэш для HTML-страниц и статики
          if (
            networkResponse.ok &&
            (event.request.headers.get('accept')?.includes('text/html') ||
             event.request.destination === 'script' ||
             event.request.destination === 'style' ||
             event.request.destination === 'image')
          ) {
            caches.open(CACHE_NAME).then((cache) => {
              cache.put(event.request, networkResponse.clone());
            });
          }
          return networkResponse.clone();
        })
        .catch(() => cachedResponse);

      return cachedResponse || fetchPromise;
    })
  );
});
`;

// ===== 4. Записываем файл =====
fs.writeFileSync(SW_FILE, swContent);
console.log(`✅ Service Worker создан!`);
